### ISSUE TITLE
Training Top-Down Models with python API

### ISSUE THREAD

**Issue by TiernonRR** [talmolab/sleap-nn#353]
Hello! I am trying to follow the updated sleap-nn api documentation to train a centered_instance model. I have trained a centroid model then trained a centered_instance model. The val/train output in the viz folder seem to properly crop and center an instance in frame, but the centered instance model fails to predict keypoints. I have also noticed that the keypoint_step values are all NaNs. I am assuming I am missing something with the centered instance training. Here is how I use the api to train such model:

```
## centered instance
model_type = "centered_instance"
model_config = get_model_config(
    init_weight="default", backbone_config="swint", head_configs=f"{model_type}"
)

model_config.backbone_config.swint.model_type = "tiny"
model_config.backbone_config.swint.pre_trained_weights = "Swin_T_Weights"

trainer_config = get_trainer_config(
    batch_size=4,
    num_workers=2,
    trainer_num_devices=1,
    shuffle_train=True,
    learning_rate=1e-3,
    save_ckpt=True,
    max_epochs=50,
    visualize_preds_during_training=True,
    keep_viz=True,
    seed=42,
    ckpt_dir=".",
    run_name=f"{model_type}_training",
    lr_scheduler="reduce_lr_on_plateau",
)

# Create TrainingJobConfig
training_job_config = TrainingJobConfig(
    data_config=data_config,
    model_config=model_config,
    trainer_config=trainer_config,
)

# Convert to omegaconf objects
sleap_nn_cfg = training_job_config.to_sleap_nn_cfg()  # validates config structure

model_trainer = ModelTrainer.get_model_trainer_from_config(sleap_nn_cfg)

# get dataloaders

train_dataset, val_dataset = get_train_val_datasets(
    train_labels=model_trainer.train_labels,
    val_labels=model_trainer.val_labels,
    config=model_trainer.config,
)
train_dataloader, val_dataloader = get_train_val_dataloaders(
    train_dataset=train_dataset,
    val_dataset=val_dataset,
    config=model_trainer.config,
    trainer_devices=model_trainer.config.trainer_config.trainer_devices,
)

# create lightning model from config

lightning_model = LightningModel.get_lightning_model_from_config(
    model_trainer.config
)

# Call the `train` method to start training the model!
model_trainer.train()

```

Could you please advise?

Thank you!

**Comment by gitttt-1234** [comment]
Hi @TiernonRR !

Could you please share the training pkg file (Sleap file exported as `.pkg.slp` and the `config.yaml`) [here](https://docs.google.com/forms/d/e/1FAIpQLSfWBwcuZH8lxGyFabMAODLjSUE4YrSCYbrrnYvXCpgBqZpcJA/viewform)? It would be helpful to debug better from our side.

Thanks,

Divya

**Comment by TiernonRR** [comment]
I just tried training with only fully-defined instances (i.e. all keypoints present) and I don't encounter the NaN issue. I had noticed that when I had used my full training set that included only partially-defined instances, I would receive this error: 

```
/storage/project/r-jmarkowitz30-0/triesenmy3/miniforge/envs/sleap-nn-env/lib/python3.12/site-packages/sleap_nn/data/instance_cropping.py:49: RuntimeWarning: All-NaN slice encountered
  diff_x = np.nanmax(pts[:, 0]) - np.nanmin(pts[:, 0])
/storage/project/r-jmarkowitz30-0/triesenmy3/miniforge/envs/sleap-nn-env/lib/python3.12/site-packages/sleap_nn/data/instance_cropping.py:52: RuntimeWarning: All-NaN slice encountered
  diff_y = np.nanmax(pts[:, 1]) - np.nanmin(pts[:, 1])
```

I think that NaNs then propagate and training fails. Is this expected behavior?

**Comment by gitttt-1234** [comment]
Hi @TiernonRR !

The .slp you uploaded references the original video files, so training can’t run unless those videos are available. Could you try one of the following approaches and share the files so that I could try to train from my end: (1) upload the source videos that the .slp points to, or (2) create a packaged SLP that embeds the labeled frames so it’s self-contained. If using the GUI, go to Predict → Export → Labeled frames. You could also run the below command if GUI is not preferred:
```python
import sleap_io as sio

labels = sio.load_slp("your_slp_file.slp")
labels.save("labels_with_embedded_imgs.pkg.slp", embed=True)

```

Let us know if you have any questions!

Thanks,

Divya

**Comment by gitttt-1234** [comment]
Hi @TiernonRR !

Apologies for the delay!

I trained a sleap-nn model with the config and the pkg.slp file you shared and I wasn't able to reproduce the issue of having train loss as `NaN`s. We did fix a couple of NaN instance handling in the latest sleap-nn release. Could you try training the model with the latest `sleap-nn` version?

Let us know if you have any questions!

Thanks,

Divya

**Comment by TiernonRR** [comment]
Thank you for providing me these! I have updated sleap-io, but unfortunately I have another error 

`
FileNotFoundError: [Errno 2] No such file or directory: 'models/centered_instance_training_1-2/train_imgs/sample_0_0.jpg'
`

Does this imply that I need to manually save these images? I apologies for the naivete. 

Thanks!

**Comment by gitttt-1234** [comment]
Hi @TiernonRR !

Could you try changing the `trainer_config.run_name` to a new name? or set the `data_config.data_pipeline_fw` to  `torch_dataset_cache_img_memory`? Currently, the data pipeline framework is set to `torch_dataset_cache_img_disk`, which implies the images are cached to disk and there seems to be some path mismatch, which is strange. However, I think either setting pipeline framework to `torch_dataset_cache_img_memory` or assigning a new name to `trainer_config.run_name` should fix this issue!

Let me know if it works!

Thanks,

Divya

**Comment by TiernonRR** [comment]
Hey @gitttt-1234 

Thank you for your info, those were the culprit of that particular issue. Unfortunately, I am still encountering NaNs during training with your config file and the embedded dataset I provided. I have created a new conda env for sleap-nn and installed sleap-io from source. Here is my environment, as I am wondering if maybe there is a package mismatch somewhere: 

`
name: sleap-nn-env-2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libuuid=2.41.2=he9a06e4_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - pip=25.2=pyh145f28c_0
  - python=3.13.9=hc97d973_101_cp313
  - python_abi=3.13=8_cp313
  - readline=8.2=h8c095d6_2
  - tk=8.6.13=noxft_hd72426e_102
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - h5py==3.15.1
      - hdmf==4.1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - ipykernel==7.1.0
      - ipython==9.6.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.1
      - jsonpickle==4.1.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lark==1.3.1
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - loguru==0.7.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistune==3.1.4
      - mpmath==1.3.0
      - multidict==6.7.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - ndx-pose==0.2.2
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pygments==2.19.2
      - pynwb==3.1.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rich-click==1.9.4
      - rpds-py==0.28.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - scipy==1.16.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentry-sdk==2.43.0
      - setuptools==80.9.0
      - simplejson==3.20.2
      - six==1.17.0
      - sleap-io==0.5.7
      - sleap-nn==0.0.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - stack-data==0.6.3
      - sympy==1.14.0
      - terminado==0.18.1
      - tifffile==2025.10.16
      - tinycss2==1.4.0
      - torch==2.8.0+cu128
      - torchmetrics==1.8.2
      - torchvision==0.23.0+cu128
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.4.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wandb==0.22.3
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - yarl==1.22.0
prefix: 
  /storage/project/r-jmarkowitz30-0/triesenmy3/miniforge/envs/sleap-nn-env-2
`

Happy, too, to look at your conda env setup and compare the diff.

**Comment by gitttt-1234** [comment]
Hi @TiernonRR !

Could you let me know how you created the slp file? Did you annotate them in the SLEAP GUI or manually created the labels object and then saved it as a `.slp` file?

Thanks,

Divya

**Comment by TiernonRR** [comment]
Hey @gitttt-1234,

I have confirmed that the visibilty flag set to True was the culprit. I iterated over the labeled frames in the training set and set the visibility of nan points to False. I am now able to train a centered instance model. Thank you for your help!

I can close this issue unless you'd like to keep it open to resolve training stability issues.

Best,
Tiernon

**Comment by gitttt-1234** [comment]
Closing this, will handle the training stability part in a separate issue!
Feel free to re-open if you have any questions!
